### ISSUE TITLE
Server crash when players join [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [Patbox/polymer#12]
```java


---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 12/29/21, 7:53 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_1113
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at com.direwolf20.buildinggadgets.common.component.BGComponent.lambda$registerWorldComponentFactories$0(BGComponent.java:37)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_1.<init>(Unknown Source)
	at dev.onyxstudios.cca._generated_.GeneratedContainerFactory_1.createContainer(Unknown Source)
	at net.minecraft.world.World.handler$beo000$initComponents(World:2608)
	at net.minecraft.world.World.<init>(World:148)
	at eu.pb4.polymer.impl.other.FakeWorld.<init>(FakeWorld.java:155)
	at eu.pb4.polymer.impl.other.FakeWorld.<clinit>(FakeWorld.java:91)
	at eu.pb4.polymer.impl.entity.InternalEntityHelpers.<clinit>(InternalEntityHelpers.java:27)
	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:233)
	at net.minecraft.server.PlayerManager.localvar$foh000$polymer_setupHandler(PlayerManager:13950)
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:169)
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:130)
	at net.minecraft.server.network.ServerLoginNetworkHandler.md605355$lambda$polymer_prePlayHandshakeHackfest$0$0(ServerLoginNetworkHandler:2031)
	at eu.pb4.polymer.impl.networking.PolymerHandshakeHandlerImplLogin.onKeepAlive(PolymerHandshakeHandlerImplLogin.java:117)
	at net.minecraft.network.packet.c2s.play.KeepAliveC2SPacket.apply(KeepAliveC2SPacket:15)
	at net.minecraft.network.packet.c2s.play.KeepAliveC2SPacket.apply(KeepAliveC2SPacket:6)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741)
	at net.minecraft.server.MinecraftServer.handler$bgd000$modifiedRunLoop(MinecraftServer:5365)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1113
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 31 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 4.19.0-8-amd64
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 3529766528 bytes (3366 MiB) / 5779750912 bytes (5512 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8482.06
	Virtual memory used (MB): 7732.36
	Swap memory total (MB): 511.00
	Swap memory used (MB): 480.18
	JVM Flags: 20 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xms4G -Xmx10G
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		adventurez: AdventureZ 1.4.6
		ae2: Applied Energistics 2 10.0.0-beta.2
		ae2wtlib: AE2WTLib 10.0.0-alpha.10
		agape_space: Space Dimensions 0.4.5
		akashictomeoftools: Akashic Tome Of Tools Fabric 1.2
		alloy_forgery: Alloy Forgery 2.0.8+1.18
		annotateddi: Annotated DI 2.0.4+1.18
		aopalliance_aopalliance: aopalliance 1.0
		apoli: Apoli 2.2.2
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.5
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		arcanus: Arcanus 1.24
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.3.5
		attributefix: AttributeFix 13.0.3
		autorun: AutoRun 0.3.0
		awesomedungeon: Awesome Dungeon 2.0.0
		awesomedungeon_ocean: Awesome Dungeon Edition Ocean 1.0.3
		balm-fabric: Balm 2.4.0+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.1.5
		bedrockwaters: BedrockWaters 1.6.0+1.18.1
		beehivetooltips: Beehive Tooltips 1.4.1
		beenfo: Beenfo 1.18-fabric0.43.1-1.3.3
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.1
		betternether: Better Nether 6.0.8
		bewitchment: Bewitchment 1.18-4
		bitsandchisels: BitsAndChisels 2.6.3
		blockshifter: Blockshifter 1.4.1+fabric-1.18
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.18-7.0.0-Fabric
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		botania: Botania 1.18.1-427-FABRIC
		bountiful: Bountiful 2.0.1
		buildinggadgets: st'ructure tools 1.0.7
		calio: Calio 1.4.2
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-level: Cardinal Components API (world saves) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		carpet-tis-addition: Carpet TIS Addition 1.28.1
		carrier: Carrier 1.9.0
		catwalksinc: Catwalks Inc. 1.1.0
		chalk: Chalk 1.2.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chisel: Chisel Refabricated 1.4.4
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.4
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_google_inject_guice: guice 5.0.1
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion_bats: Companion Bats 1.18.7
		compress: Compress 'em [v1.5]
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.18+1.18
		consistency_plus: Consistency Plus 0.4.3+1.18
		cosmetic-armor: Cosmetic Armor 1.2.0
		creativeonepunch: Creative One-Punch 1.3
		creeperspores: Creeper Spores 1.7.1
		crookedcrooks: Crooked Crooks 2.0.1+1.18.1
		croparia: Croparia 0.0.5
		croptopia: Croptopia 1.7.4
		crowdin-translate: CrowdinTranslate 1.4+1.18
		crusade: Crusade 1.2.5
		culinaire: Culinaire 2.3.3
		cursormod: Custom Cursor Mod 1.3.0
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		dankstorage: Dank Storage 1.18.1-3.3
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		dataattributes: Data Attributes 1.1.1
		dawn: Dawn API 3.2.0
		deathlog: DeathLog 0.2.4+1.18
		disenchanter: Disenchanter 0.1.4+1.18
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.0-beta2
		dml-refabricated-base: DML: Refabricated - Base 0.5.0-beta2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.0-beta2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.0-beta2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.0-beta2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.0-beta2
		doom: Doom Fabric 4.0.0
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.9
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49b-fabric
		dusk: Dusk Mod 1.18-1.7
		dynview: Dynamic View Mod 1.18-1.5
		earthtojavamobs: Earth2Java 1.7.4+1.18
		eldritch_mobs: Eldritch Mobs 1.10.2
		elementalcreepers: Elemental Creepers: Refabricated 1.4.1+1.18.1
		enchant_giver: Enchant Giver 1.1.0
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		exlineawnings: Exline's Awnings 1.18
		exlinefurniture: Exline's Furniture 1.18
		expandedstorage: Expanded Storage 7.3.4
		experiencebugfix: Experience Bug Fix 18
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		extragenerators: Extra Generators 1.1.1-BETA+1.18
		extraorigins: Extra Origins 1.18-1
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricenchantments: Fabric Enchantments 0.6.1
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		fabrictailor: Fabric Tailor 1.7.3
		fallingtree: FallingTree 2.16.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farmingforblockheads: Farming for Blockheads 9.0.2
		fastfurnace: FastFurnace 1.18-4
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireplacelib: Fireplace Lib 6.2.2+1.18
		fireworkfrenzy: Firework Frenzy 1.7
		flan: Flan 1.18-1.6.4
		fluidtank: Fluid Tank 18.2.410-fabric
		flytre_lib: FlytreLib 1.6.2
		forgeconfigapiport: Forge Config API Port 3.1.0
		friendsandfoes: Friends&Foes 1.0.2
		fryingpan: Frying Pan! 2.0.0
		geckolib3: Geckolib 3.0.23
		genesis: Genesis 1.18.1-1.0.0
		givemehats: Give Me Hats! 1.7.5
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.56
		goblintraders: Goblin Traders 1.4.1
		golemancy: Golemancy 1.1.1
		graveyard: The Graveyard 1.1
		guardiansgalore: GuardiansGalore 1.18-3.0
		hammermod: War-Hammers Mod 1.18
		hardcorequesting: Hardcore Questing Mode 1.18.1-5.9.0
		harvest_scythes: Harvest Scythes 2.4.0
		heartbond: Heartbond 1.2.0
		hologram-api: Hologram API 0.2.1+1.18-pre5
		hookshot: Hookshot 23.0
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		hyperlighting: Hyper Lighting 1.0.1
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		incantationem: Incantationem 1.1.3+1.18.1
		inmis: Inmis 2.4.0-1.18
		invview: InvView 1.4.8-1.18+
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		ironfurnaces: Iron Furnaces 3.0.0
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		javax_inject_javax_inject: javax.inject 1
		jump: Platformer 1.0.0
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kjsextras: KubeJS Extras 1.5.0
		krypton: Krypton 0.1.6
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.0-build.254
		kyrptconfig: Kyrpt Config 1.2.3-1.18
		lank: Lankasters Origins 1.0.0
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.10.0
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.4.0.1
		libraryferret: Library Ferret 1.0.1
		lifts: Lifts 1.4-BETA+1.18
		lithium: Lithium 0.7.6
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magiccombatwands: Magic Combat Wands 1.0.1
		magicfungi: Magic Fungi 0.6.2-BETA+1.18.1
		magna: Magna 1.7.0-1.18-pre1
		mambience: MAmbience 3.2.0+1.18
		marketcrates: Marketcrates 1.4.1
		mavm: More Axolotl Variants Mod 1.0.6a
		mcda: MC Dungeons Armors 1.8.6
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdict: MCDict 2.1.0+1.17.1
		mcdw: MC Dungeons Weapons 3.6.0-1.18
		mcf-reap: MaxVar reap for fabric 1.7.0
		me_hypherionmc_night-config_core: core 3.6.5_custom
		me_hypherionmc_night-config_toml: toml 3.6.5_custom
		megane: megane 6.2.0
		megane-applied-energistics-2: megane-applied-energistics-2 6.2.0+10.0.0-alpha.1
		megane-base: megane-base 6.2.0
		megane-dml-simulacrum: megane-dml-simulacrum 6.2.0+0.5.0-beta2
		megane-extra-generators: megane-extra-generators 6.2.0+1.1.1-BETA-1.18
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-kibe: megane-kibe 6.2.0+1.9.4-BETA-1.18
		megane-lib-block-attributes: megane-lib-block-attributes 6.2.0+0.10.0
		megane-modern-industrialization: megane-modern-industrialization 6.2.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.2.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.2.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.2.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		megane-wireless-networks: megane-wireless-networks 6.2.0+1.4.0
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.1.3
		milk_plus: Milk+ 2.0.0
		minecraft: Minecraft 1.18.1
		mining_dims: Mining Dimensions 1.2.38
		miningutility: Mining Utility 1.2+1.18-pre1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		mobz: MobZ 3.2.0
		mocolors: Mo' Colors 1.3.0
		modern_industrialization: Modern Industrialization 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mtmechs: Magitek Mechs 1.0.10
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mythic-mounts: Mythic Mounts 1.18-4.0
		mythicmetals: Mythic Metals 0.11.0
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.8
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		omega-config: OmegaConfig 1.2.2-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.29
		origins: Origins 1.3.1
		origins-classes: Origins: Classes 1.2.4
		overlord: Overlord 3.1.3+1.18.1
		owo: oωo 0.3.8+1.18
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18.1-63-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phonos: Phonos 0.2+1.18
		pickupnotifier: Pick Up Notifier 3.1.0
		pipe: Pipe 1.6.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		polymer: Polymer 0.2.0-beta.15+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.15+1.18.1
		polymorph: Polymorph 0.0.16-1.18.1
		prefab: Prefab 3.0.0
		publicguiannouncement: Public Gui Announcement 3.1.0.3
		pugh_lib: Pugh Lib 1.2.13
		pugh_tools: Pugh Tools 1.1.16
		puzzleslib: Puzzles Lib 3.1.3
		quarryplus: QuarryPlus 18.1.0
		quartzelv: Quartz Elevator 2.0.1+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		ratsmischief: Rat's Mischief 1.3.4
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.4
		redbits: Red Bits 1.11.0
		redstonebits: Redstone Bits 1.6.2
		repurposed_structures: Repurposed Structures 3.1.12+1.18.1
		resourceful_tools: Resourceful Tools 1.2.29
		respawnablepets: Respawnable Pets 1.18-1
		rhino: Rhino 1800.1.6-build.81
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.1.357
		ruined_equipment: Ruined Equipment 1.4.0
		sandwichmod: Sandwich Mod 1.18
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		silkspawners: SilkSpawners 1.1.0
		simple_shelves: Simple Shelves 1.0.4
		slimyfloor: Slimy Floor 1.18-1.2.2
		soaringstructures2: Soaring Structures 2 1.18 - 2.0
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		soulbound: Soulbound 2.0.0
		spectrum: Spectrum 1.1.5-1.18.1-earlygame6
		stacc: Stacc 1.2.3
		starlight: Starlight 1.0.0+fabric.d0a3220
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		storagecabinet: Storage Cabinet 1.4.2
		structurized: Structurized 1.4.0+1.18
		sushimod: Sushi Mod 1.18
		tacocraft: TacoCraft 1.7.2-1.18.1
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.1.0-beta.4
		teenycoal: Teeny Coal 1.1.0-1.16.x-1.17.x-1.18.x
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0_b0.1.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		things: Things 0.2.8+1.18
		thonkutil: ThonkUtil 2.5.0+1.18
		thonkutil-base: ThonkUtil Base 1.4.0+ee0434f8c8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.1.0+dbf3756dc8
		thonkutil-customization: ThonkUtil Customization (v1) 1.0.1+e2ecd8cdc8
		thonkutil-legacy: ThonkUtil Legacy 1.0.7+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.5+e4c51c01c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.5+769eee82c8
		tinyskeletons: Tiny Skeletons 3.1.0
		tolaserblade: ToLaserBlade 1.18-0.4.5.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		trashslot: TrashSlot 11.0.1
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		twigs: Twigs 1.1.2
		unforgivingvoid: Unforgiving Void 3.1.1+1.18
		universal-graves: Universal Graves 2.0.0-beta.3+1.18
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		urns: Urns 1.0.1
		valley: ValleyCraft 2.1
		veggie_way: The Veggie Way 1.2.26
		veinmining: Vein Mining 0.0.11-1.18
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		visualworkbench: Visual Workbench 3.1.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		ward_blocks: Ward Blocks 1.2.22
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.4.1
		wfw: Warhammer Fantasy Weapons 0.1.4-1.18
		winged: Winged Mod 1.18.1-3.1.0
		wirelessnetworks: Wireless Networks 1.4.1
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.18.9
		xlpackets: XLPackets 2.1-1.17.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Polymer (polymer), st'ructure tools (buildinggadgets)


```

**Comment by itsdinkd** [comment]
https://github.com/red2blue/AQM2/issues/26

**Comment by Patbox** [comment]
Seems like issue with that BuildingGadgets mod, as Polymer creates fake world which isn't ClientWorld or ServerWorld based (to limit required resources). That mod doesn't check if world is client one to make sure it can access things. I'm looking forward to make any required changes as needed through

**Comment by ProjectET** [comment]
We have to return something when we register a world component with CCA and returning null would not work. So we cant just fix it on our end.

**Comment by Patbox** [comment]
Maybe creating a stub would do? This world isn't (and can't be) saved/ticked anyway, so it shouldn't matter as much

**Comment by ProjectET** [comment]
i could try that give me one sec.

**Comment by ProjectET** [comment]
@red2blue could you try this jar on the server? (Unzip the zip file)
[structure-tools-1.0.7.zip](https://github.com/Patbox/polymer/files/7796076/structure-tools-1.0.7.zip)
