### ISSUE TITLE
Spectrum pedestal crafting with REI

### ISSUE THREAD

**Issue by Antoninecek** [Patbox/polymer#15]
Add items from Rei to Spectrum Pedestal (via REI plus button). Causes timeout on client and disconnect from server. Playing AQM2.

https://github.com/itsdinkd/AQM2/issues/92

rei.log
[21:37:15] [Render thread/TRACE] Built Recipe View in 228.1 ms for 0 categories, 1 recipes for, 0 usages for and 9 live recipe generators.
[21:37:18] [Render thread/TRACE] Built Recipe View in 347.4 ms for 0 categories, 1 recipes for, 0 usages for and 9 live recipe generators.
[21:37:24] [Render thread/TRACE] Built Recipe View in 258.6 ms for 0 categories, 1 recipes for, 0 usages for and 9 live recipe generators.

Now I could get something (don't know if related, because before there were no logs in the time of timeout) in latest.log
[21:37:46] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "state" is null
at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
at eu.pb4.polymer.api.block.PolymerBlockUtils.getPolymerBlockState(PolymerBlockUtils.java:106) ~[polymer-0.2.0-beta.15+1.18.1-d8b25413a92a15da.jar:?]
at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.modify$imi000$polymer_replaceBlockStateOnClient(ChunkDeltaUpdateS2CPacket:525) ~[?:?]
at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.visitUpdates(ChunkDeltaUpdateS2CPacket:72) ~[?:?]
at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkDeltaUpdate(ClientPlayNetworkHandler:654) ~[?:?]
at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:64) ~[?:?]
at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:14) ~[?:?]
at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
at net.minecraft.client.MinecraftClient.render(MinecraftClient:1080) ~[?:?]
at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]

**Comment by Patbox** [comment]
Weird, that should never really happen. It's the case only if you use rei?

**Comment by Antoninecek** [comment]
Sorry, I don't uderstand your question (I don't know what should I try). I don't have any experience with modding mc (I don't even know how Polymer works and what is his role in this case). 

However I did some scenario testing and when I try to add ingredience for orange dye (red and yellow dye) the ingrediences are not showing in pedestal for like 5 seconds (while I'm in pedestal crafting interface or not). After few seconds the recipe is in pedestal and in latest I can see error, but no disconnect.

[15:29:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "state" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
	at eu.pb4.polymer.api.block.PolymerBlockUtils.getPolymerBlockState(PolymerBlockUtils.java:106) ~[polymer-0.2.0-beta.15+1.18.1-d8b25413a92a15da.jar:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.modify$imi000$polymer_replaceBlockStateOnClient(ChunkDeltaUpdateS2CPacket:525) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.visitUpdates(ChunkDeltaUpdateS2CPacket:72) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkDeltaUpdate(ClientPlayNetworkHandler:654) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:64) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:14) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1080) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]

When I tried spectrums Bottle of Fading the ingrediences show up after 5 sec in pedestal crafting interface and in the same second they show up, I get disconnect without single error in log (just timeout message).

Everytime I try to add the recipe from REI, the rei.log gets message:
[15:30:50] [Render thread/TRACE] Built Recipe View in 286.6 ms for 0 categories, 1 recipes for, 0 usages for and 3 live recipe generators.
