### ISSUE TITLE
Client crash on server connection 1.21.1

### ISSUE THREAD

**Issue by samuel-odinware** [Patbox/polymer#156]
I am building a mod pack that works just fine on single player, but fails on the server. Any help deciphering the following error would be greatly appreciated.

```
---- Minecraft Network Protocol Error Report ----
// 404

Time: 2024-10-06 20:17:16
Description: Packet handling error

io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:commands'
	at net.minecraft.class_9136.method_56425(class_9136.java:38)
	at net.minecraft.class_9136.decode(class_9136.java:14)
	at net.minecraft.class_2543.decode(class_2543.java:31)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(256) + length(1) exceeds writerIndex(256): PooledSlicedByteBuf(ridx: 256, widx: 256, cap: 256/256, unwrapped: PooledUnsafeHeapByteBuf(ridx: 108539, widx: 110061, cap: 131072))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
	at net.minecraft.class_8703.method_53016(class_8703.java:28)
	at net.minecraft.class_2540.method_10816(class_2540.java:484)
	at net.minecraft.class_2540.method_10799(class_2540.java:321)
	at net.minecraft.class_2540.method_10787(class_2540.java:317)
	at net.minecraft.class_2641.method_11405(class_2641.java:117)
	at net.minecraft.class_2540.method_34068(class_2540.java:150)
	at net.minecraft.class_2540.method_34066(class_2540.java:163)
	at net.minecraft.class_2641.<init>(class_2641.java:61)
	at net.minecraft.class_9139$6.decode(class_9139.java:37)
	at net.minecraft.class_9139$9.method_56441(class_9139.java:91)
	at net.minecraft.class_9139$9.decode(class_9139.java:87)
	at net.minecraft.class_9136.method_56425(class_9136.java:36)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Epoll Client IO #0
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)
Mixins in Stacktrace:
	net.minecraft.class_2547:
		xyz.nucleoid.packettweaker.mixin.PacketListenerMixin (packettweaker.mixins.json)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: vanilla
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)
	at net.minecraft.class_2600.method_59803(class_2600.java:62)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_60881(class_8673.java:127)
	at net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Mixins in Stacktrace:
	net.minecraft.class_2547:
		xyz.nucleoid.packettweaker.mixin.PacketListenerMixin (packettweaker.mixins.json)
	net.minecraft.class_8673:
		xyz.nucleoid.packettweaker.mixin.client.ClientCommonNetworkHandlerMixin (packettweaker.mixins.json)
		io.wispforest.owo.mixin.ClientCommonNetworkHandlerAccessor (owo.mixins.json)
		eu.pb4.polymer.networking.mixin.client.ClientCommonNetworkHandlerMixin (polymer-networking.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.ClientCommonNetworkHandlerMixin (fabric-networking-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.ClientCommonNetworkHandlerAccessor (fabric-networking-api-v1.client.mixins.json)
		eu.pb4.polymer.common.mixin.client.ClientCommonNetworkHandlerMixin (polymer-common.mixins.json)
	net.minecraft.class_2535:
		io.github.fabricators_of_create.porting_lib.mixin.common.ConnectionMixin (porting_lib_base.mixins.json)
		xyz.nucleoid.packettweaker.mixin.ClientConnectionMixin (packettweaker.mixins.json)
		eu.pb4.polymer.common.mixin.ClientConnectionMixin (polymer-common.mixins.json)
		eu.pb4.polymer.networking.mixin.ClientConnectionAccessor (polymer-networking.mixins.json)
		net.fabricmc.fabric.mixin.networking.ClientConnectionMixin (fabric-networking-api-v1.mixins.json)
		me.steinborn.krypton.mixin.shared.network.pipeline.encryption.ClientConnectionMixin (krypton.mixins.json)
		eu.pb4.polymer.networking.mixin.ClientConnectionMixin (polymer-networking.mixins.json)
		io.wispforest.owo.mixin.ClientConnectionMixin (owo.mixins.json)
		io.github.thecsdev.tcdcommons.mixin.events.MixinClientConnection (tcdcommons.mixin.events.json)
		me.steinborn.krypton.mixin.shared.network.pipeline.compression.ClientConnectionMixin (krypton.mixins.json)
```

**Comment by Patbox** [comment]
Can you send your modlist?

**Comment by stnsxs** [comment]
Fabric Mods: 
		a_good_place: A Good Place 1.21-1.2.6
		accurateblockplacement: Accurate Block Placement 1.4.4+mc-1.20.5-1.21.1
		amber: Amber 3.0.0+1.21.1
		ambientsounds: AmbientSounds 6.3.8
		appleskin: AppleSkin 3.0.6+mc1.21
		architectury: Architectury 13.0.8
		cicada: CICADA 0.14.3+1.21-1.21.1
			org_yaml_snakeyaml: snakeyaml 2.2
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0+1.21
		creativecore: CreativeCore 2.13.39
			net_neoforged_bus: bus 7.2.0
		do_a_barrel_roll: Do a Barrel Roll 3.7.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		entity_model_features: Entity Model Features 3.2.4
		entity_texture_features: Entity Texture Features 7.1
		fabric-api: Fabric API 0.116.12+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.72+7b3d111d19
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.31+d527f9fd19
			fabric-block-api-v1: Fabric Block API (v1) 1.1.0+0bc3503219
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.11+ebb2264e19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.19+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.7+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.12.0+c3656daa19
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.7+5b36e0f719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.38+60a6976219
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.1+65213ef819
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.8.0+2b27e0a419
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.14+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.2.0+3b3cb2e819
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.7+def88e3a19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.6.0+0865547519
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.14+8aaf3aca19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.1.0+b4d813fc19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.1+d30f6a7919
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.16+2475392c19
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.3.2+e3eddc2119
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.1+b4d813fc19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.1+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.69+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.49+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.72+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.1.0+ab4c25a019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.91+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.4+7b3d111d19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabric-language-kotlin: Fabric Language Kotlin 1.13.11+kotlin.2.3.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.3.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.3.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.3.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.3.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.32.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.10.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.10.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.7.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.9.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.9.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.11.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.11.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.11.0
		fabricloader: Fabric Loader 0.19.2
			mixinextras: MixinExtras 0.5.4
		fallingtree: FallingTree 1.21.1.11
		forgeconfigapiport: Forge Config API Port 21.1.6
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		freecam: Freecam 1.3.0+mc1.21
		gammautils: Gamma Utils 2.1.2
		geckolib: GeckoLib 4 4.8.4
		hold-my-items: Hold My Items 4.3
		inventoryprofilesnext: Inventory Profiles Next 2.2.6
		iris: Iris 1.8.8+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemphysic: ItemPhysic 1.8.13
		jade: Jade 15.10.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.27.0.340
		lambdynlights: LambDynamicLights 4.8.8+1.21.1
			lambdynlights_runtime: LambDynamicLights (Runtime) 4.8.8+1.21.1
				lambdynlights_api: LambDynamicLights (API) 4.8.8+1.21.1
					yumi_commons_collections: Yumi Commons: Collections 1.0.0
					yumi_commons_core: Yumi Commons: Core 1.0.0
					yumi_commons_event: Yumi Commons: Event 1.0.0
				pride: Pride Lib 1.2.4+1.21.1
				spruceui: SpruceUI 6.2.5+1.21.1
				yumi_mc_core: Yumi Minecraft Libraries: Foundation 1.0.0-beta.1+1.21.1
		libipn: libIPN 6.6.3
		liteminer: Liteminer 1.0.3+1.21.1
		malilib: MaLiLib 0.21.10
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.25.1+mc1.21.1
		modmenu: Mod Menu 11.0.4
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moonlight: Moonlight Lib 1.21.1-3.0.14
		mousetweaks: Mouse Tweaks 2.26
		mru: M.R.U 1.0.19+LTS+1.21.1+fabric
			org_commonmark_commonmark: commonmark 0.21.0
		ok_zoomer: Ok Zoomer 10.0.0-beta.13
			wrench_wrapper: Wrench Wrapper 0.8.1
			wrench_wrapper_backend: Wrench Wrapper (Backend) 0.8.1
		resourcify: Resourcify 1.8.1
		skinlayers3d: 3d-Skin-Layers 1.11.1
			transition: TRansition 1.0.17
			trender: TRender 1.0.12
		sodium: Sodium 0.6.13+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.10
		tweakeroo: Tweakeroo 0.21.61
		xaerominimap: Xaero's Minimap 25.3.12
			xaerolib: XaeroLib 1.1.15
		xaeroworldmap: Xaero's World Map 1.40.16
		yet_another_config_lib_v3: YetAnotherConfigLib 3.8.2+1.21.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

**Comment by Patbox** [comment]
Create a new issue with actual error
