### ISSUE TITLE
Conflict with quickcarpet

### ISSUE THREAD

**Issue by mackdroid** [Patbox/polymer#29]
```Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:22:20] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[14:22:21] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[14:22:21] [main/WARN]: Warnings were found!
 - Mod 'QuickCarpet' (quickcarpet) 3.4.0 recommends version 0.11.5 of malilib, which is missing!
	 - You should install version 0.11.5 of malilib for the optimal experience.
[14:22:21] [main/INFO]: Loading 56 mods:
	- autoconfig1u 3.2.0-unstable via iamverysmart
	- cardinal-components-base 4.0.0 via fabrichomes
	- cardinal-components-entity 4.0.0 via fabrichomes
	- cloth-basic-math 0.5.1 via cloth-config2
	- cloth-config2 4.5.6 via iamverysmart
	- fabric 0.51.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.0+bd8a4a1860 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via styledchat
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-tpa 3.1.0
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabrichomes 2.2.0
	- fabricloader 0.13.3
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- iamverysmart 2.1.0+mc1.16.1
	- java 17
	- minecraft 1.18.2
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- placeholder-api 1.1.3+1.17.1 via styledchat
	- polymer 0.2.0-pre.5+1.18.2 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-pre.5+1.18.2 via polymer
	- quickcarpet 3.4.0
	- quickcarpet-api 1.1.0 via quickcarpet
	- server_translations_api 1.4.12+1.18.2 via universal-graves
	- sgui 1.0.2+1.18.2 via universal-graves
	- skinrestorer 1.0.4
	- styledchat 1.2.2+1.18
	- universal-graves 2.0.2+1.18.2
[14:22:21] [main/WARN]: Mod `polymer-legacy` (0.1.9+0.2.0-pre.5+1.18.2) does not respect SemVer - comparison support is limited.
[14:22:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/mcs3/mcs/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:22:21] [main/INFO]: Compatibility level set to JAVA_16
[14:22:21] [main/INFO]: Compatibility level set to JAVA_17
[14:22:22] [main/INFO]: Applying Fabric API Registry Sync workaround
[14:22:23] [main/WARN]: @Redirect conflict. Skipping quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin->@Redirect::quickcarpet$redirectGetId(Lnet/minecraft/class_2378;Ljava/lang/Object;)Lnet/minecraft/class_2960; from mod quickcarpet with priority 1000, already redirected by polymer.mixins.json:compat.fabric.fabricSync_RegistrySyncManagerMixin->@Redirect::polymer_skipVirtualObjects(Lnet/minecraft/class_2378;Ljava/lang/Object;Z)Lnet/minecraft/class_2960; from mod polymer with priority 1000
[14:22:23] [main/WARN]: @Redirect conflict. Skipping quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin->@Redirect::quickcarpet$redirectGetId(Lnet/minecraft/class_2378;Ljava/lang/Object;)Lnet/minecraft/class_2960; from mod quickcarpet with priority 1000, already redirected by polymer.mixins.json:compat.fabric.fabricSync_RegistrySyncManagerMixin->@Redirect::polymer_skipVirtualObjects(Lnet/minecraft/class_2378;Ljava/lang/Object;Z)Lnet/minecraft/class_2960; from mod polymer with priority 1000
[14:22:23] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zdi000$set(class_2370.java:1053) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:134) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40282(class_2378.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40283(class_2378.java:330) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zdi000$set(class_2370.java:1053) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:134) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40282(class_2378.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40283(class_2378.java:330) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector quickcarpet$redirectGetId(Lnet/minecraft/class_2378;Ljava/lang/Object;)Lnet/minecraft/class_2960; in quickcarpet.mixins.json:fabricApi.RegistrySyncManagerMixin from mod quickcarpet failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap quickcarpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.handler$zdi000$set(class_2370.java:1053) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:86) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:134) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10227(class_2378.java:354) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40282(class_2378.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40283(class_2378.java:330) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
```

**Comment by Patbox** [comment]
Report it to them, as I can't replace this mixin. They are mixing into fabric api's registry sync and I also need to do that

**Comment by Patbox** [comment]
Couldn't you just use regular carpet mod instead?

**Comment by mackdroid** [comment]
> Couldn't you just use regular carpet mod instead?

same issue with regular carpet too, my bad i should have provided the output for it aswell.

> Report it to them, as I can't replace this mixin. They are mixing into fabric api's registry sync and I also need to do that

Ah i wasnt sure on where to report this issue, i will try opening a issue there aswell

**Comment by Patbox** [comment]
Could you get error with regular carpet? Since it shouldn't collide

**Comment by mackdroid** [comment]
pardon my negligence, i just realised i didnt remove quick carpet while testing with carpet and the error was related to that i just tried freshly with just polymer and fabric and it does work, i will close this issue
and thank you for the work you do for server side fabric plugins!

**Comment by Patbox** [comment]
It's best to keep it open until it gets fixed on their side, just so I won't get duplicates. Just report it to them :p
