### ISSUE TITLE
Crash when loading world with REI

### ISSUE THREAD

**Issue by Trnrr** [Patbox/polymer#34]
Game crashes when I try to load into any singleplayer world

Versions:
Quilt 0.17.1-beta.4

Polymer 0.2.0-rc.4.1+1.18.2(packed by some mod)
RoughlyEnoughItems-8.3.501.jar
architectury-4.5.75-fabric.jar
cloth-config-fabric-6.2.62.jar
polymer-all-0.2.0-rc.4.1+1.18.2.jar
qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2.jar

I'm not sure which mod is packing it, but I tried with the latest off modrinth and get the same crash.

![image](https://user-images.githubusercontent.com/20446954/176555429-541cb67b-1df3-479d-a3cc-27de895ae4fb.png)

```
Time: 6/29/22, 5:10 PM
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "me.shedaniel.rei.impl.common.entry.type.EntryRegistryList.needsHash()" because "this.registryList" is null
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.removeEntryIf(EntryRegistryImpl.java:224)
	at eu.pb4.polymer.impl.client.compat.ReiCompatibility.lambda$registerEvents$2(ReiCompatibility.java:47)
	at eu.pb4.polymer.api.utils.events.SimpleEvent.invoke(SimpleEvent.java:26)
	at eu.pb4.polymer.impl.client.InternalClientRegistry.clear(InternalClientRegistry.java:305)
	at eu.pb4.polymer.impl.client.InternalClientRegistry.disable(InternalClientRegistry.java:140)
	at net.minecraft.class_310.handler$zkj000$polymer_onDisconnect(class_310.java:5504)
	at net.minecraft.class_310.method_18096(class_310.java:2196)
	at net.minecraft.class_310.method_18099(class_310.java:2159)
	at net.minecraft.class_310.method_29610(class_310.java:2003)
	at net.minecraft.class_310.method_29606(class_310.java:1937)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:431)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:340)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_526.method_19945(class_526.java:70)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.rei.impl.common.entry.type.EntryRegistryImpl.removeEntryIf(EntryRegistryImpl.java:224)
	at eu.pb4.polymer.impl.client.compat.ReiCompatibility.lambda$registerEvents$2(ReiCompatibility.java:47)
	at eu.pb4.polymer.api.utils.events.SimpleEvent.invoke(SimpleEvent.java:26)
	at eu.pb4.polymer.impl.client.InternalClientRegistry.clear(InternalClientRegistry.java:305)
	at eu.pb4.polymer.impl.client.InternalClientRegistry.disable(InternalClientRegistry.java:140)
	at net.minecraft.class_310.handler$zkj000$polymer_onDisconnect(class_310.java:5504)
	at net.minecraft.class_310.method_18096(class_310.java:2196)
	at net.minecraft.class_310.method_18099(class_310.java:2159)
	at net.minecraft.class_310.method_29610(class_310.java:2003)
	at net.minecraft.class_310.method_29606(class_310.java:1937)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:431)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:340)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_526.method_19945(class_526.java:70)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1147)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2383)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)```

**Comment by Patbox** [comment]
Update to latest polymer for 1.18.2 (0.2.0-rc.4.2+1.18.2)
