### ISSUE TITLE
Using Velocity + NoChatReports breaks with polymer

### ISSUE THREAD

**Issue by skyfsj** [Patbox/polymer#75]
sendGameJoinBeforeSync is enabled

```Velocity log
13:27:08 INFO]: [server connection] fsj -> New_Vanilla has connected
[13:27:09 INFO]: [server connection] fsj -> Old_Vanilla has disconnected
[13:27:09 ERROR]: [server connection] fsj -> New_Vanilla: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@577977ef
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```
```polymer log
[13:27:09] [Netty Epoll Play IO Thread #0/ERROR]: Received class net.minecraft.class_7861 that couldn't be processed
java.lang.ClassCastException: class eu.pb4.polymer.networking.impl.PolymerHandshakeHandlerImplLogin cannot be cast to class net.minecraft.server.network.ServerPlayNetworkHandler (eu.pb4.polymer.networking.impl.PolymerHandshakeHandlerImplLogin and net.minecraft.server.network.ServerPlayNetworkHandler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @e25b2fe)
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.handler$dgc000$nochatreports$onHandle(PlayerSessionC2SPacket.java:525) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:175) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:160) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:52) ~[server-intermediary.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by Patbox** [comment]
It's bug with no chat reports, not polymer.Report there

**Comment by Patbox** [comment]
If they don't care, neither should I

**Comment by elhertz** [comment]
> If they don't care, neither should I

There's an open issue about this https://github.com/Aizistral-Studios/No-Chat-Reports/issues/410 
I think they closed the one mentioned before bc it was a duplicate (I hope so)

**Comment by Patbox** [comment]
They knew about the issue enough time with fix being simple (which they also know about), yet many versions later it's still an issue so
