### ISSUE TITLE
Virtual passengers are removed from the backing list by value instead of index

### ISSUE THREAD

**Issue by haykam821** [Patbox/polymer#84]
According to [the `fastutil` documentation](https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/IntArrayList.html#removeInt(int)), the `IntArrayList#removeInt` method uses indices instead of arrays:

> #### `public int removeInt(int index)`
> Removes the element at the specified position in this list (optional operation).

However, in both `VirtualEntityUtils.removeVirtualPassenger` methods, Polymer passes values, rather than the index of each value, to the removal method:

https://github.com/Patbox/polymer/blob/f715dbf08bfd87025bad5460786932c7a9ade730/polymer-virtual-entity/src/main/java/eu/pb4/polymer/virtualentity/api/VirtualEntityUtils.java#L46-L56

As a result, when attempting to remove a virtual passenger, an exception such as the following is thrown:

```
java.lang.IndexOutOfBoundsException: Index (1578) is greater than or equal to list size (24)
        at it.unimi.dsi.fastutil.ints.IntArrayList.removeInt(IntArrayList.java:359)
        at eu.pb4.polymer.virtualentity.api.VirtualEntityUtils.removeVirtualPassenger(VirtualEntityUtils.java:47)
```

**Comment by haykam821** [comment]
Fixed in 68a20c78c40791368c343b3721ac5d05301ca1d2
