### ISSUE TITLE
Fabric 1.20.1 0.14.24 mixin crash with polymer 0.5.18

### ISSUE THREAD

**Issue by SettingDust** [Patbox/polymer#95]
What cloud causing this? It's fine before.
`org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Redirect handler method net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager::polymer_registry_sync$skipServerEntries from polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator has an invalid signature. Found 1 unexpected additional method arguments: (boolean) [INJECT Applicator Phase -> polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator -> Apply Injections ->  -> Inject -> polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator->@Redirect::polymer_registry_sync$skipServerEntries(Lnet/minecraft/class_2378;Ljava/lang/Object;Z)Lnet/minecraft/class_2960;]`
```
[11:21:18] [main/ERROR] (FabricLoader) Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$cfa000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$cfa000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator] from phase [DEFAULT] in config [polymer-rsm.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$cfa000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Redirect handler method net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager::polymer_registry_sync$skipServerEntries from polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator has an invalid signature. Found 1 unexpected additional method arguments: (boolean) [INJECT Applicator Phase -> polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator -> Apply Injections ->  -> Inject -> polymer-rsm.mixins.json:fabric.fabricSync_RegistrySyncManagerMixin from mod polymer-registry-sync-manipulator->@Redirect::polymer_registry_sync$skipServerEntries(Lnet/minecraft/class_2378;Ljava/lang/Object;Z)Lnet/minecraft/class_2960;]
	at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:604) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.invoke.RedirectInjector.injectAtInvoke(RedirectInjector.java:384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.invoke.RedirectInjector.inject(RedirectInjector.java:325) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2370.onChange(class_2370.java:677) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.handler$cfa000$fabric-registry-sync-v0$set(class_2370.java:672) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47478(class_7923.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47488(class_7923.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.method_47489(class_7923.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	... 5 more
```

**Comment by SettingDust** [comment]
Know the reason. There is 1.20.2 fabric api bundled by another mod
